### ISSUE TITLE
how to use plugin block bootstap

### ISSUE THREAD

**Issue by baihaqyaviq** [jd-dotlogics/laravel-grapesjs#10]
how to use bootstrap plugin block?

**Comment by jd-dotlogics** [comment]
Hi @baihaqyaviq! For now there is no option for adding plugin.

**Comment by vahidalvandi** [comment]
please add this option

**Comment by jd-dotlogics** [comment]
Hopefully will work on it in next one or two weeks.

**Comment by vahidalvandi** [comment]
i have idea for change layout with grapesjs 
Suppose we have a special order in a blade and we want to change it with grapesjs page builder

**Comment by jd-dotlogics** [comment]
> i have idea for change layout with grapesjs Suppose we have a special order in a blade and we want to change it with grapesjs page builder

Blade content already is changeable with page build via templates.

**Comment by jd-dotlogics** [comment]
Hi @baihaqyaviq, The bootstarp4 plugin option was added in the latest release. please see [v3.1.0](https://github.com/jd-dotlogics/laravel-grapesjs/releases/tag/3.1.0)
