### ISSUE TITLE
Laravel 9 Implementation 

### ISSUE THREAD

**Issue by Ang3ls** [jd-dotlogics/laravel-grapesjs#16]
HI, Thanks for this package!

I am trying to insert it in a Laravel 9 installation with:

`composer require jd-dotlogics/laravel-grapesjs`

but 

`  Problem 1
    - jd-dotlogics/laravel-media[2.0.0, ..., 2.0.8] require illuminate/support ~5.6.0|~5.7.0|~5.8.0|^6.0|^7.0|^8.0 -> found illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - jd-dotlogics/laravel-grapesjs[3.0.0, ..., 3.x-dev] require jd-dotlogics/laravel-media ^2 -> satisfiable by jd-dotlogics/laravel-media[2.0.0, ..., 2.0.8].
    - Root composer.json requires jd-dotlogics/laravel-grapesjs ^3.0 -> satisfiable by jd-dotlogics/laravel-grapesjs[3.0.0, 3.x-dev].`

i am new to the laravel world but i think my problem is that within the composer.json of the project :

`jd-dotlogics/laravel-media`

I can't find compatibility with Laravel 9

`        "illuminate/support": "~5.6.0|~5.7.0|~5.8.0|^6.0|^7.0|^8.0",`

Do you have any suggestions for solving this?

Kind Regards

**Comment by jd-dotlogics** [comment]
Hi, I need to fix this issue -- But I'm very busy now a days and will update soon.

**Comment by jd-dotlogics** [comment]
Hi, The bug was resolved in the latest release. please see [v3.1.0](https://github.com/jd-dotlogics/laravel-grapesjs/releases/tag/3.1.0)
