### ISSUE TITLE
Svg images to the custom blocks and templates

### ISSUE THREAD

**Issue by 0xSheff** [jd-dotlogics/laravel-grapesjs#19]
Hello JD,

Is it possible to add some svg image to custom templates and blocks, which is added to the views/vendor/laravel-grapesjs/gjs-blocks and templates directories?

![image](https://user-images.githubusercontent.com/12431039/169772173-7ba1c7cd-893b-42bc-b2dc-ea74ce19f0bc.png)

**Comment by jd-dotlogics** [comment]
Hi @0xSheff, This option added in new release -- please see Release 3.2.3

**Comment by insssomniac** [comment]
Hi JD, 

Great, thanks a lot!

**Comment by 0xSheff** [comment]
Hi JD,

Great, thanks a lot!
