### ISSUE TITLE
csrf token mismatch

### ISSUE THREAD

**Issue by seongbae** [jd-dotlogics/laravel-grapesjs#25]
Hi,

Thank you for the package.  I'm trying to use your package on my project... everything seems to work fine except when I try to upload an image, it shows "CSRF token mismatch".   How do I attach CSRF token when uploading images?

Thank you.

Seong

**Comment by mjawad096** [comment]
Hi @seongbae, please provide more details. Like which version you are using? From where you uploading image? etc.

**Comment by Edgarborras94** [comment]
The same happens to me, it appears to be empty on the meta tags:

`
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="csrf-token" content="">
`
I will try to find the template of this and try to append the csrf token to see if its working.

Running latest Laravel 9 version as of today and PHP 8.1 on Laravel Valet.

If I find the reason before @mjawad096 will try to do a PR ;)

nice work btw @mjawad096

**Comment by jd-dotlogics** [comment]
Bug fixed please updated to [v3.2.5](https://github.com/jd-dotlogics/laravel-grapesjs/releases/tag/3.2.5)
