### ISSUE TITLE
I do not have settings in right toolbar from some time

### ISSUE THREAD

**Issue by sergeynilov** [jd-dotlogics/laravel-grapesjs#37]
Hello,
using laravel-grapesjs( "3.3.0" ) from some time settings in right toolbar on selected element (like https://prnt.sc/2GwbfSRTwHAr )
disappeared for selected element.
In /config/laravel-grapesjs.php I have options :

```
    'plugins' => [
        'default' => [
            'basic_blocks' => true,
            'bootstrap4_blocks' => false,
            'image_editor' => true,
            'custom_fonts' => [],
            'templates' => true,
        ],
        'custom' => [

```
I tried to modify them , but no  settings visible anyway.
1) How can I restore those  settings in right toolbar ?
2) What for those default plugins ? where are they described ?

Thanks!

**Comment by jd-dotlogics** [comment]
Hi @sergeynilov, Please set [limited_selectors](https://github.com/jd-dotlogics/laravel-grapesjs/blob/3.3.0/src/config.php#L93) to false in your config file.

**Comment by emincer** [comment]
I have this same issue, April 2023, on Laravel 9. And I did set limited_selectors to false.
