### ISSUE TITLE
How can I create and use custom AssetManager 

### ISSUE THREAD

**Issue by sergeynilov** [jd-dotlogics/laravel-grapesjs#41]
In laravel 8 app with "jd-dotlogics/laravel-grapesjs": "^3" I need to modify images editor,like adding 
custom inputs and additive parameters to server's request when reading images
I see that AssetManager is used and at link https://grapesjs.com/docs/modules/Assets.html#customization
I read about customization of assets and wonder in which way I can create and use custom AssetManager in jd-dotlogics/laravel-grapesjs plugin ?

Thanks!

**Comment by jd-dotlogics** [comment]
You can create a custom plugin for that (as explained [here](https://github.com/jd-dotlogics/laravel-grapesjs/issues/36#issuecomment-1165350859)) or you can modify the core configurations (as explained [here](https://github.com/jd-dotlogics/laravel-grapesjs/issues/18#issuecomment-1132712115) ) and then you can add your required changes there.
