### ISSUE TITLE
Doesnt work with 7.4

### ISSUE THREAD

**Issue by IrfanShlj** [jd-dotlogics/laravel-grapesjs#42]
This version needs PHP8. It fails in earlier versions due to the union types declarations in PluginManager.

**Comment by m-faizanrasool** [comment]
I'm facing the same issue

**Comment by jd-dotlogics** [comment]
The bug has been resolved in [3.4.0 ](https://github.com/jd-dotlogics/laravel-grapesjs/releases/tag/3.4.0)
