### ISSUE TITLE
images save in base64.

### ISSUE THREAD

**Issue by nazar-goyda** [jd-dotlogics/laravel-grapesjs#43]
Hello. I have a problem. Image  not save in storage, and converts it to base64, and does not save it anywhere. How can I fix this?
https://prnt.sc/fCNNgc9MuwGa

Laravel 8.0

**Comment by jd-dotlogics** [comment]
@nazar-goyda which version are you using? Please share your config file (laravel-grapesjs.php).

**Comment by jd-dotlogics** [comment]
I hope your problem gets resolved, So closing this issue here.
