### ISSUE TITLE
Body background is not saves

### ISSUE THREAD

**Issue by insssomniac** [jd-dotlogics/laravel-grapesjs#44]
Hello!

There is a bug (?) when I added some background-image to the 'body' element it saves, but if I refresh the editor the body style is cleared and there is no background-image property in the code.

For some reasons it is important to add the picture to the body background in my case. Please advice is it possible to fix this?

**Comment by jd-dotlogics** [comment]
@insssomniac currently it is not possible to add background to the body as the body is just container fo grapesjs and it will not saved in database.
