### ISSUE TITLE
i can't add custom plugin

### ISSUE THREAD

**Issue by joukhar** [jd-dotlogics/laravel-grapesjs#45]
i tried to add image editor but it shows me the following error :
`editor.js:2 The defination for plugin 'image-editor' not found.`

i added it in custom plugins exemple

```

 'custom' => [
            'grapesjs-custom-code' => 'https://unpkg.com/grapesjs-custom-code',
            [
                'enabled' => true,
                'name' => 'image-editor',
                'styles' => [
                    'https://cdnjs.cloudflare.com/ajax/libs/tui-image-editor/3.15.3/tui-image-editor.min.css',
                ],
                'scripts' => [
                    'https://unpkg.com/tui-image-editor',
                ],
                'options' => [
                    //plugin options goes here
                ],
      ]]

```

2 -  how i can remove iframe component .

Do u have any solution please  .

**Comment by jd-dotlogics** [comment]
Hi There, thanks for using my package.

1. The image editor is already added to the package and disabled by default. You can enable it from the config by setting [image_editor](https://github.com/jd-dotlogics/laravel-grapesjs/blob/3.3.0/src/config.php#L149) to true
2. Currently there is no way to remove the iframe component.
