### ISSUE TITLE
Older version of Grapesjs

### ISSUE THREAD

**Issue by m-faizanrasool** [jd-dotlogics/laravel-grapesjs#46]
Hi I'm using your package and it is working nice.

But You are using the older version of Grapesjs that uses "display: table" to design rows and cells.  // 0.18.4
I want to use the latest version of Grapesjs that supports flex box to design. // 0.19.5

How can I use the latest version of Grapesjs in your package?

**Comment by jd-dotlogics** [comment]
Hi Faizan,

Thanks for using my package. But for now, there is no way to update the core Grapesjs package. I'll update it soon.

Or you can submit a PR for updating.

Thanks.

**Comment by jd-dotlogics** [comment]
The gjs updated, see  [v3.4.0 ](https://github.com/jd-dotlogics/laravel-grapesjs/releases/tag/3.4.0)

**Comment by m-faizanrasool** [comment]
Hi thanks for updating the core grapesjs in your package

I have updated to the 3.4.0 

I have another question for you
how can I customize the basic blocks of grapesjs
Like in Grapesjs we can tell the basic blocks to use flexGrid, as by default it's using table layout
I need to change to flexGrid.

In the config file how can I tell the basic blocks to use flexGrid.
I tried something like this but it's not working
`' 'plugins' => [
        'default' => [
            'basic_blocks' => [
                    'flexGrid' => 1,
                    'stylePrefix' => '',
                ],
            'bootstrap4_blocks' => false,
            'code_editor' => true,
            'image_editor' => false,
            'custom_fonts' => [],
            'templates' => true,
        ],
...,
]`
there is only option to set it true or false but I need to tell here to use flexGrid.

**Comment by jd-dotlogics** [comment]
Hello @m-faizanrasool, Currently there is no way to pass the options to default plugins.

But you can disable it from the default, and then add it in the custom plugins as below (I've not tested it, confirm here if it works for you).

```PHP
'plugins' => [
    'default' => [
        ....
        'basic_blocks' => false
        ....
    ],
    'custom' => [
        ...
        [
            'enabled' => true,
            'name' => 'gjs-blocks-basic',
            'options' => [
                'flexGrid' => 1,
                'stylePrefix' => '',
            ],
            'scripts' => 'https://cdn.jsdelivr.net/npm/grapesjs-blocks-basic@1.0.1/dist/index.min.js',
        ],
        ...
    ]
]
```

**Comment by m-faizanrasool** [comment]
Yes that's working, Thanks

But I don't want to use it through cdn.
is there any other way to use that?

**Comment by m-faizanrasool** [comment]
Great, Thanks
