### ISSUE TITLE
image editor returns black screen 

### ISSUE THREAD

**Issue by joukhar** [jd-dotlogics/laravel-grapesjs#47]
in config 

```
    'default' => [
            'basic_blocks' => true,
            'bootstrap4_blocks' => false,
            'code_editor' => true,
            'image_editor' => true,
            'custom_fonts' => [],
            'templates' => true
        ],

```

screenshot : `https://prnt.sc/WggH-yulJCBa`

**Comment by jd-dotlogics** [comment]
Hello there, Have you removed the image editor from the custom plugins in the config? If so, please try a hard refresh or incognito window

**Comment by joukhar** [comment]
ok i will try.

**Comment by joukhar** [comment]
it doesn't work

**Comment by jd-dotlogics** [comment]
Can you please open this link [http://127.0.0.1:8000/storage/editor/media/Screenshot%202022-09-05%20235720.png](http://127.0.0.1:8000/storage/editor/media/Screenshot%202022-09-05%20235720.png) in your browser and let me know if it returning the image or not?

If it shows an error page instead of an image, you might be not created the storage link.

**Comment by joukhar** [comment]
it returns image.

**Comment by jd-dotlogics** [comment]
Have you tried with a different image?

**Comment by joukhar** [comment]
yes

**Comment by OmarAlwabsi** [comment]
Hi
I think the problem is caused by using a Fake domain  for example: http://laravel-grapesjs.test

The problem is in:
Dotlogics\Grapesjs\App\Http\Controllers\AssetController

    private function replaceLocalUrlToFilePath($url)
    {
        $urlParts = parse_url($url);
        if ($urlParts['host'] == 'localhost') {
            return [public_path($urlParts['path']), true];
        }

        return [$url, false];
    }

the solution :

    private function replaceLocalUrlToFilePath($url)
    {
        $urlParts = parse_url($url);
        // if ($urlParts['host'] == 'localhost') {
        //     return [public_path($urlParts['path']), true];
        // }

        if ($urlParts['host'] == request()->getHttpHost()) {
            return [public_path($urlParts['path']), true];
        }

        return [$url, false];
    }

**Comment by joukhar** [comment]
thanks , finally it works
