### ISSUE TITLE
error runing editor w.extend is not function

### ISSUE THREAD

**Issue by mohamad-supangat** [jd-dotlogics/laravel-grapesjs#52]
![image](https://user-images.githubusercontent.com/48933993/189497478-b3dc17d9-869c-441f-b903-6e43b967784b.png)

"name": "jd-dotlogics/laravel- "version": "3.4.0"

**Comment by michaelgatuma** [comment]
Experiencing same error. I am on laravel 8.83, php 8.1.3, and "jd-dotlogics/laravel-grapesjs": "3.4.0"
To reproduce, visit the model editor route as in the documentation.

**Comment by mohamad-supangat** [comment]
> Experiencing same error. I am on laravel 8.83, php 8.1.3, and "jd-dotlogics/laravel-grapesjs": "3.4.0" To reproduce, visit the model editor route as in the documentation.

yes after update to "3.4.0" get error, same error in new fresh laravel install

**Comment by jd-dotlogics** [comment]
You can use 3.3.* for now, I'll look into but it can take some time.
