### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by psycrow117** [jd-dotlogics/laravel-grapesjs#55]
Hi, May I know how to add custom font on the typography for this one? I checked `laravel-grapesjs.php` and there is a custom_fonts under plugins. I tried this but the font still wont appear.

`
'plugins' => [
        'default' => [
            'basic_blocks' => false,
            'bootstrap4_blocks' => false,
            'code_editor' => true,
            'image_editor' => false,
            'custom_fonts' => [
                [
                    'value'=>'Barlow, sans-serif',
                    'name'=>'Barlow',
                ],
            ],
            'templates' => false,
        ]
]
`

**Comment by jd-dotlogics** [comment]
@psycrow117 I see that the internal plugin is not working. You can create a custom plugin (as Explained [here](https://github.com/jd-dotlogics/laravel-grapesjs/issues/36#issuecomment-1165350859)) for that and add fonts through that.
