### ISSUE TITLE
Open Style Manager don't show options

### ISSUE THREAD

**Issue by web1989** [jd-dotlogics/laravel-grapesjs#58]
Hello
Why don't these options appear? https://ibb.co/ZVt5P8x

**Comment by mjawad096** [comment]
Hello, you can enable it from the config by changing the [limited_selectors](https://github.com/jd-dotlogics/laravel-grapesjs/blob/ba2da912c8fac82f8fb9640fd4a890fab8dbf6bd/src/config.php#L94)  to false.
