### ISSUE TITLE
Documentation or Tutorial

### ISSUE THREAD

**Issue by somato-tomato** [jd-dotlogics/laravel-grapesjs#6]
Hello,

Thank you for create a wonderful Package, but im wondering is there any documentation or tutorial ?

Thank you.

**Comment by jd-dotlogics** [comment]
Hi @somato-tomato! have you reviewed the Read me file -- Is this not enough?

**Comment by somato-tomato** [comment]
Hi thanks for reply. i try to upload image but the image not uploaded.

**Comment by somato-tomato** [comment]
okay i need to do 
`php artisan vendor:publish --provider="Dotlogics\Media\MediaServiceProvider" --tag="migrations"`
Thank you.

**Comment by jd-dotlogics** [comment]
> okay i need to do `php artisan vendor:publish --provider="Dotlogics\Media\MediaServiceProvider" --tag="migrations"` Thank you.

Added this to Readme file
