### ISSUE TITLE
how to append block manager to another element

### ISSUE THREAD

**Issue by joukhar** [jd-dotlogics/laravel-grapesjs#61]
hi 
please tell me how to append block manager to another element , please give me example 
note : I know how to add custom plugin .
and thanks for your efforts

**Comment by jd-dotlogics** [comment]
@joukhar did not get your point? Is the problem solved now? If so, please share what was the problem and how you solve it.

**Comment by joukhar** [comment]
i created a config file like you mentioned  in one question 

exemple :
```
(function (w) {
    try {
        if (w.editorConfig) {
      
    } catch (e) { }
})(window)
```
