### ISSUE TITLE
401 Unauthorized on Save

### ISSUE THREAD

**Issue by nomentsoa-andrianjatovo** [jd-dotlogics/laravel-grapesjs#66]
After page load, I have `GET http://foo.test/laravel-grapesjs/App-Models-Content/1/templates 500 (Internal Server Error)` in the JS console.
Then when clicking the Save Icon, I have `401 Unauthorized`.
https://imgur.com/a/nO8gAAL

**Comment by jd-dotlogics** [comment]
Hi @nomentsoa-andrianjatovo, not able to reproduce it on my end. Are you still facing the issue? If so, Have you tried the latest version?

 If you resolved this issue please share your finding. Or share steps, on how we can reproduce it.

**Comment by hoangk51** [comment]
> After page load, I have `GET http://foo.test/laravel-grapesjs/App-Models-Content/1/templates 500 (Internal Server Error)` in the JS console. Then when clicking the Save Icon, I have `401 Unauthorized`. https://imgur.com/a/nO8gAAL

You must login or In file config/laravel_grapejs.php  , comment auth middleware 
 'routes' => [
        'middleware' => [
            'web', //'auth',
        ],
    ],
