### ISSUE TITLE
How to activate Style Manager?

### ISSUE THREAD

**Issue by pajkho** [jd-dotlogics/laravel-grapesjs#68]
First of all. Really great and easy package!

I was wondering if anyone has managed to activate the Style Manager? See below screenshot.

![bild](https://user-images.githubusercontent.com/8545572/211177894-6ea7866e-5050-4f3e-a0b3-7dfed50bfa3f.png)

**Comment by marlon33** [comment]
> First of all. Really great and easy package!
> 
> I was wondering if anyone has managed to activate the Style Manager? See below screenshot.
> 
> ![bild](https://user-images.githubusercontent.com/8545572/211177894-6ea7866e-5050-4f3e-a0b3-7dfed50bfa3f.png)

config/laravel-grapesjs.php
line 109 change of true to false
```php
    'style_manager' => [
        'limited_selectors' => true,
    ],
```
![image](https://user-images.githubusercontent.com/41172965/218264213-3799c18e-80d8-4150-976e-1dc4919223f3.png)

```php
    'style_manager' => [
        'limited_selectors' => false,
    ],
```

![image](https://user-images.githubusercontent.com/41172965/218264173-60331280-ed96-430d-824b-17b620fdf386.png)
