### ISSUE TITLE
I can't load new block and templates

### ISSUE THREAD

**Issue by excinober** [jd-dotlogics/laravel-grapesjs#69]
Hi,

What is the exactly route and file format for create the blocks and templates?

Thanks!

**Comment by jd-dotlogics** [comment]
Hi, Please have look at [placeholders](https://github.com/jd-dotlogics/laravel-grapesjs#placeholders) and [templates](https://github.com/jd-dotlogics/laravel-grapesjs#templates) on the readme. Let us know if it didn't help you.

Thanks.
