### ISSUE TITLE
How can i show the page in a specific route?

### ISSUE THREAD

**Issue by marlon33** [jd-dotlogics/laravel-grapesjs#71]
I wish to know how can i show the page :id in a specific route, like:

https://domain.com/page-tag

**Comment by jd-dotlogics** [comment]
@marlon33 you can create a simple route and render a blade file in it and pass the loaded page to that blade file. Copy and paste the below lines into your blade file. 

```blade
<style type="text/css">
	{!! $page->css !!}
</style>

{!! $page->html !!}

```
