### ISSUE TITLE
How to store the html without the body tag

### ISSUE THREAD

**Issue by fuadkm** [jd-dotlogics/laravel-grapesjs#72]
I'm trying to implement page builder for content section only. How can i remove the body tag from the editor? 
Prevent the wrapper from the html part while saving the data.

**Comment by jd-dotlogics** [comment]
@fuadkm the body tag is not saved in the database it is only for display in the editor.

**Comment by fuadkm** [comment]
@jd-dotlogics But, when i save the body tag is getting saved in the database. Please see the attachment


<div id="main-content">
    <div id="main-page-content">

        {!! $folio->html !!}

    </div>
    
 This is what i get


--
  | <div id="main-content">
  | <div id="main-page-content">
  |  
  | <body><div id="ife2" class="light-section-wrapper">
