### ISSUE TITLE
How to add plugins

### ISSUE THREAD

**Issue by J87NL** [jd-dotlogics/laravel-grapesjs#9]
Hi! Thanks for creating this package!

Can you please share some instructions how to add plugins like https://github.com/artf/grapesjs-plugin-forms to the config?
Is this possible?

Kind regards,
Johan.

**Comment by jd-dotlogics** [comment]
Hi Johan, Thanks for using my package.

Sadly! For now, there is no option/config for adding plugins to the editor dynamically. But if you set true `exposeApi` in the config, an instance of the editor will be available via `window.gjsEditor`. You can look into that it helps.

Thanks,
JD.

**Comment by J87NL** [comment]
Hi JD,
Thanks for your fast reply!
I tried that method and was able to access window.gjsEditor, unfortunatly I don't know how to add plugins from there. I hoped you might know a way?
Kind regards,
Johan.

**Comment by jd-dotlogics** [comment]
Sorry, I think it may help you -- But I think it is not possible to added plugins after initialization of editor. So I it seems not possible to add a new plugin to it. I'll working on it and will update package to add custom plugins. But for that you may have to wait as I'm busy now a day.

**Comment by jd-dotlogics** [comment]
Sorry, I thought it may help you -- But I think it is not possible to added plugins after initialization of editor. So I it seems not possible to add a new plugin to it for now. I'll working on it and will update package to add custom plugins. But for that you may have to wait as I'm busy now a day.

**Comment by vnsinfo** [comment]
Hi JD
Thanks for this amazing code. It has helped us a lot.
Had a small request. The version of grapesjs used in this package seems to be quite old. The latest editor has a lot of new features.  
I am especially after the tab component. Is there any easy way of updating/using the latest version of the editor.
Thanks in advance.

Kind Regards
Hemant

**Comment by jd-dotlogics** [comment]
Will work on it in next one or two weeks.

**Comment by insssomniac** [comment]
Hi JD
If you have a chance, please give a short explanation of the config file - it seems it is possible to connect some scripts and styles in the 'scripts' and 'styles' sections, and what mean the 'image_editor'? Could you please give little example how to connect style file, if it is possible to connect scss file to access it inside editor.
Thanks for the great product.

**Comment by jd-dotlogics** [comment]
> Hi JD If you have a chance, please give a short explanation of the config file - it seems it is possible to connect some scripts and styles in the 'scripts' and 'styles' sections, and what mean the 'image_editor'? Could you please give little example how to connect style file, if it is possible to connect scss or css file to access it inside editor. Thanks for the great product.

Hi, the styles and scripts are the global sheets you may need to apply to your content. e.g bootstrap files. -- THe "image_editor" option is to enable image manipulation (See [](https://github.com/artf/grapesjs-tui-image-editor) ) after the image uploaded

**Comment by jd-dotlogics** [comment]
Hi @J87NL, Now you can plugin from config, I've added your mentioned plugin in config by default -- Please see release [3.2.0](https://github.com/jd-dotlogics/laravel-grapesjs/releases/tag/3.2.0)
